apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize-hello-world

commonLabels:
  app: kustomize-hello-world

commonAnnotations:
  splunk.com/index: kustomize

namePrefix: prefix-
nameSuffix: -dce
namespace: gdpr

resources:
- deployment.yaml
