apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize-hello-world

resources:
- deployment.yaml

patchesJson6902:
  - target:
      group: apps 
      version: v1
      kind: Deployment
      name: nginx-deployment
    path: update.yaml
